### ISSUE TITLE
Google 翻译配置项示例错误

### ISSUE THREAD

**Issue by forever2077** [mouyong/translate#11]
// Google翻译
$translator = new TranslateHelper();
$translator->translator = 'google';

// 需按照以下数组才能成功请求
$translator->config = [
    'http' => [
        'verify' => false,
        'proxy' => 'http://127.0.0.1:27890',
    ],
];

$rtn = $translator->translate('你好');
dump($rtn);
$this->assertEquals('hello', $rtn['dst']);`

**Comment by mouyong** [comment]
是不是使用上哪里用错了。我测试是可以的。


![image](https://github.com/mouyong/translate/assets/10336437/c783838d-a6b6-4a8e-9dd7-ee2c2376ce5b)

**Comment by mouyong** [comment]
这个代理地址是我内部的地址。替换成自己的代理地址就可以了。

**Comment by forever2077** [comment]
谢谢回复，项目很不错，已经找到导致问题发生原因，我未配置好CA文件，只要完成php.ini的curl.cainfo配置就解决，或者在参数中指定 verify = false 或 verify = 'cacert.pem' 也可以解决，thx
