### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by yanhaidao-bjhl** [mouyong/translate#2]
[InvalidArgumentException]                                                                                                                                                      
  Could not find a version of package mouyong/translate matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.  
                                                                                                                                                                                  

Exception trace:
 () at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/src/Composer/Command/InitCommand.php:726
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/src/Composer/Command/InitCommand.php:394
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/src/Composer/Command/RequireCommand.php:122
 Composer\Command\RequireCommand->execute() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/src/Composer/Console/Application.php:254
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/src/Composer/Console/Application.php:103
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/1.6.3/libexec/composer.phar/bin/composer:56
 require() at /usr/local/Cellar/composer/1.6.3/libexec/composer.phar:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by mouyong** [comment]
@yanhaidao-bjhl 使用的镜像源是？

**Comment by yanhaidao-bjhl** [comment]
"repositories": {
    "packagist": {
      "type": "composer",
      "url": "https://packagist.phpcomposer.com"
    }
  }

**Comment by yanhaidao-bjhl** [comment]
是镜像源的问题。感谢~

**Comment by mouyong** [comment]
那我 close issue 了。
