### ISSUE TITLE
jingsan翻译不可用?

### ISSUE THREAD

**Issue by otary** [mouyong/translate#6]
金山翻译，根据代码的请求调用，返回的是455的状态码，这是为什么呢？
![image](https://user-images.githubusercontent.com/3916327/163301762-614ac4ca-c9b9-491b-a5b5-7cd4af8a4869.png)

**Comment by justmd5** [comment]
我修复了下，等合并

**Comment by mouyong** [comment]
刚看到消息。抱歉抱歉。
