### ISSUE TITLE
谷歌翻译translate.google.cn会自动跳转到translate.google.com，因此访问不了

### ISSUE THREAD

**Issue by otary** [mouyong/translate#8]
谷歌翻译translate.google.cn会自动跳转到translate.google.com，所以谷歌翻译没法使用，现在有新的方案吗?

**Comment by mouyong** [comment]
谷歌的吗，我看看

**Comment by mouyong** [comment]
尝试更换请求的域名从 translate.google.cn 到 translate.google.com。尝试使用代理试试。

看看请求配置种，增加配置跟随请求跳转后，能否正常请求。

**Comment by mouyong** [comment]
@otary 你可以配置 http 代理，以达到使用 google 翻译。

项目已重构，发布了新版本。

支持通过配置 http 来配置 guzzle 选项。仅 google provider 需要。

**Comment by mouyong** [comment]
已重构 v3，提供了代理示例，测试可使用。
