### ISSUE TITLE
composer require "mouyong/translate"    安装报错

### ISSUE THREAD

**Issue by kokobing** [mouyong/translate#9]
安装后，会报如下错误

In helpers.php line 15:
                                                           
  Class "HigherOrderTapProxy\HigherOrderTapProxy" not fou  
  nd

**Comment by mouyong** [comment]
@kokobing 相关文件在这里，你看下 vendor 目录里面，这个 helper.php 是否包含如下内容。许久未给 support 发版了。可能是这个依赖包的旧版本未包含下方代码的原因导致的。

https://github.com/mouyong/php-support/blob/master/src/helpers.php#L11-L24

**Comment by mouyong** [comment]
我看了下，之前的 tag 有包含这部分代码，你是在什么情况下安装的呢？

https://github.com/mouyong/php-support/blob/v1.0.32/src/helpers.php

**Comment by kokobing** [comment]
今天尝试composer update 还是有报错，我用的是PHP8.1 LARAVEL9
<img width="725" alt="图片" src="https://user-images.githubusercontent.com/4141904/197426088-7572a3fb-731c-4028-b70c-543d491473bc.png">

**Comment by mouyong** [comment]
我测试排查一下。

**Comment by mouyong** [comment]
已修复，写错了类名导致的。

**Comment by kokobing** [comment]
嗯嗯，好的，非常感谢！

**Comment by mouyong** [comment]
已重构 v3
